### ISSUE TITLE
Remote parquet data sources?

### ISSUE THREAD

**Issue by snunez1** [ak-coram/cl-duckdb#20]
The following example of loading a parquet file uses a file on local disk:
```
(ddb:initialize-default-connection)
(ddb:query "SELECT * FROM '~/Downloads/yellow_tripdata_2023-01.parquet' LIMIT 5" nil)
```
The [duckdb FROM clause](https://duckdb.org/docs/sql/query_syntax/from) doesn't seem to offer http download as an option.

Edit:  There is [HTTP Parquet Import](https://duckdb.org/docs/guides/import/http_import), but it requires the `httpfs` extension to be installed.  Any way to do that?

Another thing to consider is a wrapper, similar to the way that Lisp-Stat does in [read-csv](https://github.com/Lisp-Stat/dfio/blob/5caf473acb9bc464839e87395724cbd941167915/delimited-text.lisp#L24) that wraps multiple stream protocols so the user doesn't have to be concerned with the location of the source. The [I/O simplification](https://github.com/Lisp-Stat/dfio/blob/5caf473acb9bc464839e87395724cbd941167915/utils.lisp#L60) is where the work is done.

**Comment by ak-coram** [comment]
> There is HTTP Parquet Import, but it requires the httpfs extension to be installed. Any way to do that?

I think running `(ddb:query "INSTALL httpfs;" nil)` should do the trick.

> Another thing to consider is a wrapper, similar to the way that Lisp-Stat does in read-csv that wraps multiple stream protocols so the user doesn't have to be concerned with the location of the source. The I/O simplification is where the work is done.

This all happens in DuckDB internally and I don't think we can change it in a meaningful way in the driver. It's not even part of the C API, it's all controlled via SQL statements which are just strings as far as cl-duckdb is concerned.

**Comment by snunez1** [comment]
Ah, this make sense now.  It really is a database, and C API is not the recommended/supported API.  My mental model was something like Apache Arrow.

If that's the case, have you considered making duckdb a supported part of [clsql](https://www.cliki.net/CLSQL/), a multi-platform SQL interface for Common Lisp?  This would give you access to [CommonSQL](http://www.lispworks.com/documentation/sql-tutorial/), a nice SEXP syntax for SQL, a CLOS/ORM system and is generally a nice way to interact with database systems from Common Lisp.

**Comment by ak-coram** [comment]
> C API is not the recommended/supported API

It is a well supported official API, most of the different language bindings use it. DuckDB itself is written in C++, so AFAIK you can do some things via C++ which are not (yet) available via the C API.

> have you considered making duckdb a supported part of clsql, a multi-platform SQL interface for Common Lisp?

I've looked into it and while it could be done, DuckDB already provides an API compatible with SQLite and also a driver for ODBC, so you could just use one of those backends with clsql if you wanted. Those APIs seem to be more suited towards how clsql models databases in the first place. This project on the other hand tries to leverage the DuckDB-specific C API to get better performance (e.g. working with [data chunks](https://duckdb.org/docs/api/c/data_chunk.html), [appenders](https://duckdb.org/docs/api/c/appender.html), etc.) and support features which aren't covered by clsql at all (e.g. [table functions](https://duckdb.org/docs/api/c/table_functions)). I'm sorry, but all things considered I currently have no incentive to do this. If someone wanted to, it could easily be done as a separate project building on top of cl-duckdb (maybe only reusing the low-level bindings from `duckdb-api.lisp`).

**Comment by snunez1** [comment]
What I think I miss the most from clsql is CommonSQL.  Badly.  Writing SQL text strings is painful.  Maybe something like [sxql](https://github.com/fukamachi/sxql)?  We'd have to be careful about the transient dependencies there though; fukamachi doesn't look too carefully at the tree, though he has in the past agreed to modify libs for a 'clean' license dependency tree.

**Comment by snunez1** [comment]
@ak-coram, they do, and it could probably be passed in, somehow, to duckdb.  I've had 'split out CommonSQL from clsql' on my to-do list for a while.  Perhaps in the meanwhile, we could provide an example of how sxql would be used to pass along a string, so that others could at least get going with that as a pattern or idiom?

As an FYI, as a personal preference, I find that good documentation and examples can paper over a lot of coding.  For example the entire duckdb/dataframe integration (all two lines of it!) is [simply documenting how it's done](https://lisp-stat.dev/docs/manuals/data-frame/#from-parquet-files).

The `(ddb:query "INSTALL httpfs;" nil)` does work and we can close this now.

**Comment by ak-coram** [comment]
Ok, thank you for the update! I've created issue #25 for dealing with the documentation.
