### ISSUE TITLE
Phase out cl-str dependency

### ISSUE THREAD

**Issue by Symbolics** [ak-coram/cl-duckdb#26]
`cl-str` has a dependency on [cl-change-case](https://github.com/rudolfochrist/cl-change-case/), which is GPL licensed.

**Comment by ak-coram** [comment]
This should be fairly straightforward: we just need replacements for `concat`, `param-case`, `downcase`, `join` and `replace-all`. There's also one call to `snake-case` in the tests, but that can be substituted with `replace-all`. We'll also need to update the docs, since they use `concat` too.

**Comment by sirherrbatka** [comment]
cl-str is rather… questionable to be honest but indeed all of it can be implemented quite easily.

(defun concat (&rest strings) (format nil "~{~a~}" strings) ; or test types beforehand if you feel like it, also join can be done by using ~^ in format
(defun downcase (string) (check-type string string) (string-downcase string)) ; or just use cl:string-downcase directly
replace-all -> use substitute. check-type if you want

Wanna PR?

**Comment by ak-coram** [comment]
`replace-all` is more tricky (it replaces substrings, not just characters), I've retained cl-ppcre for now to implement it. We can replace that too in the future.
