### ISSUE TITLE
Phrase out trivia dependency

### ISSUE THREAD

**Issue by Symbolics** [ak-coram/cl-duckdb#27]
Trivia is (was?) a transitive dependency, possibly via ironclad via uuid.  It's definitely not from ascii-table, spark nor let-plus.  Mostly this is a reminder to check (is there a way to print the dependency tree with ASDF? That would be quite useful).

**Comment by ak-coram** [comment]
With PR #28 now merged, trivia is not a dependency of cl-duckdb anymore. I don't know whether a dependency tree can be printed with ASDF, but it would be indeed useful.
