### ISSUE TITLE
About that NULL handling again…

### ISSUE THREAD

**Issue by sirherrbatka** [ak-coram/cl-duckdb#30]
I had to think about it for a while, but I am reaching an opinion now. NULL should always be indicated by :NULL in CL. Let me explain why I think so.

1) NULL values are messing up booleans AND everything represented by lists on the cl side. An empty list is not always the same as NULL.
2) Assuming that the user is required to write a specific query to distinguish NULL values makes for problems when building libraries on top of duckdb (leaky abstraction).
3) It is just a more convenient solution for the user. One less thing to remember while using the package.
4) It is a solution already well proven by postmodern.

This is obviously my private opinion.

**Comment by ak-coram** [comment]
Thank you for sharing your thoughts. I understand your point, but I don't think the current defaults are that bad. They are are in line with how CL itself treats booleans, empty lists and nil. CL programmers already expect these values to be the same and using a truthy value for NULLs (such as :null) can result in some bad egonomics (all control flow requires dealing with :null separately).

Also this is probably mostly an issue for booleans and I think that allowing NULLs in a boolean column is probably a bad choice in the first place.

On the other hand I absolutely agree with your second point, I can see how this can be painful when writing libraries on top of cl-duckdb (when you are not really in control of the queries you run), so my suggestion would be the following:

1. Keep the defaults as they are, this avoids breaking changes.

2. Introduce special variable for controlling what to return for NULL values, so this can be configured according to the preferences of the user.

3. Introduce keyword argument for query functions to override this.

You could use the third option (or dynamically bind said variable) when building your library to force the use of :null regardless of user preference.

What do you think?

**Comment by sirherrbatka** [comment]
Well, sadly NULL in a boolean column will pop up from time to time because you may be querying foreign parquet files and you have no control over what people are putting in there. Furthermore, NULL is used as either "lack of information", "not yet determined", or "not applicable" in data sets at a rather frequent rate. This is just a widely accepted semantic, and not much can be done with it.

The proposed strategy sounds reasonable to me.
