### ISSUE TITLE
Figure out a way to remove trivial-with-current-source

### ISSUE THREAD

**Issue by ak-coram** [ak-coram/cl-duckdb#35]
@snunez1: It looks like our witch-hunt based on licensing can never end! This is also a non-permissively licensed dependency pulled in by esrap which itself is pulled in by local-time-duration. It looks like they have a single call to it here:

https://github.com/enaeher/local-time-duration/blob/fa20a4a03a1ee076eada649796e2f2345c930c21/iso8601.lisp#L156

Maybe we can resolve it with the project itself (it is licensed under MIT itself), but it hasn't seen any activity for 5 years now.

@enaeher: Hello! Would you be so glad and chime in on this? Your project includes a transitive dependency under the LGPLv3, which is more restrictive than the MIT license your project itself is licensed under. We'd like to keep using local-time-duration for representing duration values that come out of DuckDB (see this project for details): would you be open to a discussion on how we could resolve this issue? Thank you!

**Comment by ak-coram** [comment]
I'm sorry for my oversight, I see it's not just the one call to it (it's only one qualified call).

Esrap however only seems to use it for one thing:
https://github.com/scymtym/esrap/blob/d806138342a6b27327649fd5f36e0fe2e0966867/src/macros.lisp#L172

Esrap (MIT) and trivial-with-current-source-form (LGPLv3) seem to be maintained by the same person. They are also the author of trivial-with-current-source-form, maybe they would be willing to change the license?

**Comment by snunez1** [comment]
It's certainly worth asking them, and it looks like you already did.  I'll monitor.

**Comment by ak-coram** [comment]
@snunez1: ah, I didn't ask yet. The above was about local-time-duration and I don't think they can help us with this. 

@scymtym: Hi, we're having a licensing issue with a transitive dependency you authored. The project in question is trivial-with-current-source (LGPLv3) which is used by the MIT licensed esrap library. Would you consider any changes to remove the dependency from esrap or maybe even simply changing the license for trivial-with-current-source itself? Thank you!

**Comment by scymtym** [comment]
For trivial-with-current-source-form, I have talked to the other contributor and we can change the license to match esrap's.

**Comment by ak-coram** [comment]
@scymtym: Excellent, thank you!

**Comment by ak-coram** [comment]
@scymtym: thank you again for the change! I've seen the repository has now been updated with the new license.

@snunez1: I think this is was the last one, once there's a new quicklisp release we should automatically pull the new version.
