### ISSUE TITLE
Round trip example? 

### ISSUE THREAD

**Issue by snunez1** [ak-coram/cl-duckdb#39]
Is it possible to 'round trip' data to and from CL and a duckdb table?  One that includes any valid types?

For example if I get an alist from `ddb:query`, can I then use that somehow in the `with-static-table` macro to recreate the table, with a different name?

**Comment by ak-coram** [comment]
Yes, this wouldn't be hard to implement, but it would be naturally limited to the column types we support for static-tables. I'll look into it soon.
