### ISSUE TITLE
Type mapping

### ISSUE THREAD

**Issue by snunez1** [ak-coram/cl-duckdb#40]
I've spent some time looking at how to easily map to/from data frames.  Whilst of course anything is possible, the exercise is turning out to be a bit more painful than it perhaps needs to be.  The main problem is in tacking on the duckdb type into the alist of column values in `with-static-table`  This is turning out to be somewhat unwieldy, and prevents us from easily manipulating the data `alist` from the CL side.

There is an analogous situation in Lisp-Stat when we load CSV files, and there we pass an alist that [specifies the mapping for missing values](https://lisp-stat.dev/docs/manuals/data-frame/#missing-values).  The problem we're trying to solve is that we have no way of knowing what the input might use as a missing value, nor what the user might want as a missing value in his data frame.

Should we consider an `alist` to map types in duckdb?  Perhaps as a special variable that can be set globally for a system that's using `cl-duckdb` as a driver, or overridden in a `let` as required? 

Here's a sketch of how that might work in the case of Lisp-Stat: I use column (vector) types defined in the generic system [numerical-utilities](https://github.com/Lisp-Stat/numerical-utilities), such as `simple-double-float-vector`, `simple-fixnum-vector`, `simple-boolean-vector`, etc.  Using `cl-duckdb` as a driver, I want to map these to cl-duckdb, like so:
```
'((simple-double-float-vector . duckdb-double)
  (simple-single-float-vector . duckdb-real)
 ...)
```
You can see this used in [delimited-text.lisp](https://github.com/Lisp-Stat/dfio/blob/master/delimited-text.lisp).

I may have over-engineering the description in this issue.  Basically I'm trying to find a way to separate the data `alist` from the type information and more easily work with the data alist in CL.

**Comment by ak-coram** [comment]
Can't you just use a function to combine the two? For example:

```lisp
(defun combine-alists (&rest args)
  (loop :with result := nil
        :for alist :in args
        :do (loop :for (k . v) :in alist
                  :do (push v (alexandria:assoc-value result k 
                                                      :test 'string=)))
        :finally (return (nreverse result))))
```

Then use the result as a table:

```lisp
(ddb:with-static-table
    ("mytable" (combine-alists `(("a" . :duckdb-integer) 
                                 ("b" . :duckdb-boolean) 
                                 ("c" . :duckdb-varchar))
                               `(("a" . #(1))
                                 ("b" . #(T))
                                 ("c" . #("sajt")))))
  (ddb:query "SELECT * FROM mytable" nil))
```

**Comment by ak-coram** [comment]
I mean we could of course also change the interface, but are we going to add a new alist every time some information about a column needs to be represented? That seems a bit unwieldy too.

**Comment by snunez1** [comment]
I see this as a one-time mapping, not every time a column needs updated.  Every time we see a simple-double-float vector, it maps to `duckdb-double`.  The global variable holding the type mapping can be consulted for any column we need to convert.

**Comment by snunez1** [comment]
The library itself would use it to do the mappings so they don't have to be tacked onto the data values in the alist.

**Comment by ak-coram** [comment]
Oh you mean like this?
https://github.com/ak-coram/cl-duckdb/blob/main/duckdb-static-table.lisp#L47

These are the specialized array types we currently support and where the column type is already inferred (it's enough to just pass the vector as a value in the alist). It contains all the numeric types we can directly copy via:
https://github.com/ak-coram/cl-duckdb/blob/main/duckdb-static-table.lisp#L152

This covers the examples you mentioned except the fixnum vector, I guess we could map that to `:duckdb-bigint` as well. I'm not sure making this dynamic provides an advantage, since in addition to the column type we also need to know how these can be copied into a DuckDB data chunk.

**Comment by snunez1** [comment]
That looks similar.  The main goal here is to be able to take a CL alist and pass it to duckdb more conveniently, meaning without wrangling the alist to insert type.  If we can infer types, it's a much easier user experience.

My reason for suggesting a global is that the user might want to infer domain specific types (like `simple-double-float-vector`), and by having a user-provided mapping we can do that.

**Comment by ak-coram** [comment]
Works for me, I'll try to come up with something and will let you know! I'm sorry I didn't quite get it earlier.

**Comment by ak-coram** [comment]
The following should now work, please let me know what you think:

```lisp
(let ((duckdb-api:*static-table-type-map*
        `(((simple-array fixnum) . :duckdb-bigint)))
      (column (make-array '(2) :element-type 'fixnum
                               :initial-contents (list most-negative-fixnum
                                                       most-positive-fixnum))))
  (ddb:with-static-table ("mytable" `(("mycolumn" . ,column)))
    (ddb:query "SELECT * FROM mytable" nil)))
```

I currently check the type via `subtypep`

**Comment by ak-coram** [comment]
@snunez1: did you have a chance to take a look at this? Can I close this issue? Thanks!

**Comment by ak-coram** [comment]
I'm closing this issue, please open a new one if necessary.
