### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by atgreen** [ak-coram/cl-duckdb#66]
I am getting this now:
https://github.com/ocicl/cl-duckdb/actions/runs/11024177322/job/30618440986#step:2:7538

Any ideas?

**Comment by ak-coram** [comment]
Interesting, the error comes from here (this was added about a year ago):
https://github.com/ak-coram/cl-duckdb/blob/726917a60612ac953e5a0313088a4a2b3233f0e9/duckdb.lisp#L944

My own CI is working fine on several platforms and implementations: https://github.com/ak-coram/cl-duckdb/actions/runs/11021851793

What I can't easily say from your repository is how you install the DuckDB library. As you can see loading toplevel already runs queries against it. Which version of DuckDB is used? I only test against 1.0.0 and 1.1.1 currently.

**Comment by atgreen** [comment]
0.10.3. I'm upgrading now....  https://github.com/ocicl/ocicl-sandbox/commit/87a8a015ca6eaf745ddb83d90c46d4fd472b9b80

**Comment by ak-coram** [comment]
@atgreen did that help? The most recent run seems to have succeeded.

**Comment by atgreen** [comment]
Yes, it did!  Thanks.
